# Medical Diagnosis with Support Vector Machines(Diabetes or not)

## Task 1: Import Libraries



In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

## Task 1: Get Data

In [2]:
column_names = ["pregnancies", "glucose", "bpressure", "skinfold", "insulin", "bmi", "pedigree", "age", "class"]
df = pd.read_csv("data.csv", names=column_names)
df.shape


(768, 9)

In [3]:
df.head()

pregnancies  glucose  bpressure  skinfold  insulin   bmi  pedigree  age  \
0            6      148         72        35        0  33.6     0.627   50   
1            1       85         66        29        0  26.6     0.351   31   
2            8      183         64         0        0  23.3     0.672   32   
3            1       89         66        23       94  28.1     0.167   21   
4            0      137         40        35      168  43.1     2.288   33   

   class  
0      1  
1      0  
2      1  
3      0  
4      1

## Task 1: Extract Features

In [4]:
X = df.iloc[:,:8]
X.head()

pregnancies  glucose  bpressure  skinfold  insulin   bmi  pedigree  age
0            6      148         72        35        0  33.6     0.627   50
1            1       85         66        29        0  26.6     0.351   31
2            8      183         64         0        0  23.3     0.672   32
3            1       89         66        23       94  28.1     0.167   21
4            0      137         40        35      168  43.1     2.288   33

## Task 1: Extract Class Labels

In [5]:
y = df['class']
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: class, Length: 768, dtype: int64

## Task 2: Split Dataset

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(576, 8)
(192, 8)
(576,)
(192,)


## Task 2: Normalize Features

In [7]:
scaler = StandardScaler() # normalising all the values of X_train using scalar method
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_train[:5,:] # cannot use head method here as scalar transform gives numpy array

array([[ 1.50755225, -1.01521454, -0.40451932, -1.31921491, -0.71823753,
        -1.22070104, -0.98325882, -0.04863985],
       [-0.82986389, -0.09964691, -0.61509602,  0.9287299 ,  0.08374747,
         0.13719053, -0.62493647, -0.88246592],
       [-1.12204091, -0.95207195,  0.54307587, -1.31921491, -0.71823753,
         0.0240329 ,  0.39884168, -0.5489355 ],
       [ 2.38408331,  0.59492164,  0.64836422,  1.36583027,  2.05458297,
         0.87900167,  0.17903049,  2.03592532],
       [ 1.50755225,  0.75277813,  0.54307587,  1.55315901,  0.39089067,
         0.71555175,  0.50724171,  0.53503839]])

## Task 3: Training a Support Vector Machine

In [8]:
clf = svm.SVC(kernel='sigmoid')
clf.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

## Task 3: Decision Boundary

In [9]:
y_pred = clf.predict(X_train)
print(y_pred)
print(accuracy_score(y_train, y_pred))

[0 0 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0
 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 1 0 0
 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0
 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1 0 0 0 0 1 1
 0 0 1 1 0 0 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 0 1 0 1
 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 0 0 1 1
 0 0 1 0 0 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 1
 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0
 1 1 0 0 0 1 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0
 1 0 1 0 1 0 1 0 0 1 0 0 

## Task 3: SVM Kernels

In [10]:
#comparing different kernals
for k in ('linear','poly','rbf','sigmoid'):
    clf = svm.SVC(kernel=k)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_train)
    print(k)
    print(accuracy_score(y_train, y_pred))

linear
0.7638888888888888
poly
0.7934027777777778
rbf
0.8246527777777778
sigmoid
0.6510416666666666


## Task 4: Instantiating the Best Model

In [11]:
#we got the best method as kernal="rbf"
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_train)
    
print(accuracy_score(y_train, y_pred))

0.8246527777777778


## Task 4: Making a single prediction

In [12]:
# "pregnancies", "glucose", "bpressure", 
# "skinfold", "insulin", "bmi", 
# "pedigree", "age", "class"


## Task 4: Testing Set Prediction

In [13]:
patient = np.array([[ 1., 200., 75., 40., 0., 45.,1.5, 20. ],])
patient = scaler.transform(patient)
pred = clf.predict(patient)
pred

array([1], dtype=int64)

In [14]:
patient = np.array([[ 1., 20., 75., 40., 0., 45.,1.5, 20. ],])
patient = scaler.transform(patient)
pred = clf.predict(patient)
pred

array([0], dtype=int64)

In [16]:
#comparing 1st value of test set.....comparision of actual and predicted value
patient = np.array([X_test.iloc[0]])
patient = scaler.transform(patient)
pred = clf.predict(patient)

print("predicted value:",pred)
print("actual value:",y_test.iloc[0])

predicted value: [1]
actual value: 1


In [17]:
#comparing 2nd value of test set.....comparision of actual and predicted value
patient = np.array([X_test.iloc[1]])
patient = scaler.transform(patient)
pred = clf.predict(patient)

print("predicted value:",pred)
print("actual value:",y_test.iloc[1])

predicted value: [0]
actual value: 0


## Task 5: Accuracy on Testing Set

In [18]:
X_test = scaler.transform(X_test)
y_pred_test = clf.predict(X_test)
print(accuracy_score(y_test, y_pred_test))

0.7760416666666666


## Task 5: Comparison to All-Zero Prediction

In [19]:
y_zero=np.zeros(y_test.shape)
print(accuracy_score(y_test, y_zero))

0.6770833333333334


## Task 5: Precision and Recall

In [20]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.90      0.84       130
           1       0.71      0.52      0.60        62

    accuracy                           0.78       192
   macro avg       0.75      0.71      0.72       192
weighted avg       0.77      0.78      0.77       192

